# Generated by Django 3.2.9 on 2021-11-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='higher_education',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
