# Generated by Django 3.2.9 on 2021-11-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0004_auto_20211115_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.teacher'),
        ),
    ]
