# Generated by Django 3.2.9 on 2021-11-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0007_alter_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
